name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.2', '8.3', '8.4']
        laravel: ['11.*', '12.*', '13.*']

        include:
          - laravel: 11.*
            testbench: 9.*
          - laravel: 12.*
            testbench: 10.*
          - laravel: 13.*
            testbench: 11.*

        exclude:
          - laravel: 13.*
            php: '8.2'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: >
            dom, curl, libxml, mbstring, zip, pcntl,
            pdo, sqlite, pdo_sqlite, bcmath,
            soap, intl, gd, exif, iconv, imagick, fileinfo

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

      - name: Install dependencies
        run: |
          composer require \
            "laravel/framework:${{ matrix.laravel }}" \
            "orchestra/testbench:${{ matrix.testbench }}" \
            --dev \
            --no-interaction \
            --no-update

          composer update --prefer-dist --no-interaction -W

      - name: Execute tests
        run: vendor/bin/phpunit
