name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.2, 7.3, 7.4, 8.0, 8.1]
        laravel: [6.*, 7.*, 8.*, 9.*]
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 6.*
            stability: prefer-lowest
          - laravel: 7.*
            stability: prefer-lowest
          - laravel: 8.*
            stability: prefer-lowest
          - laravel: 9.*
            stability: prefer-lowest
          - laravel: 6.*
            php: 8.1
          - laravel: 7.*
            php: 8.1
          - laravel: 8.*
            php: 7.2
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4
        include:
          - laravel: 6.*
            testbench: 4.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*
          - laravel: 9.*
            testbench: 7.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
